disabled_rules: # rule identifiers to exclude from running
- weak_delegate

excluded:
- Pods
- fastlane
- vendor

line_length: 110

type_body_length:
  - 300
  - 400

file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
identifier_name:
  min_length:
    error: 4
  excluded:
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"
