language: swift
osx_image: xcode11.6
podfile: Podfile

before_install:
  - gem install fastlane --no-document
  - brew install swiftlint

jobs:
  include:
    - stage: Swiftlint
      script:
        - swiftlint
